### PR TITLE
Miriam

### PR DESCRIPTION
**Pull request by nakiwuge**
hey team, kindly check out my story

### CODE REVIEW

**Comment by kimbugp** [comment]
interesting story miriam

**Review by kcharles52 — COMMENTED** [review]
Thank you for the effort to practice using git and making sure you adhere to the team's call, however, I am only seeing a change to the readME file. Where can I find your story? Thank you

**Comment by zaabu** [comment]
Hello Miriam, thanks for the story. I noticed that you changed the format of the document(from doc to pages) though. Therefore I am not able to view your story at the moment.

**Review by zaabu — APPROVED** [review]
Thanks for the great story.

**Pull request merged**
